[variables]
PORT = "5000"
ENV = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
LOG_FORMAT = "json"

# Redis Configuration (adjust URLs based on your cloud provider)
REDIS_URL = "redis://localhost:6379/0"
RATE_LIMIT_STORAGE = "redis://localhost:6379/1"

# Security
REQUIRE_AUTH = "false"
API_KEY = "production-api-key-change-me"

# Features
ENABLE_SWAGGER = "true"
METRICS_ENABLED = "true"

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "curl"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -c 'from app import app; print(\"✅ Flask app imported successfully\")'",
    "python -c 'import config; print(\"✅ Configuration loaded successfully\")'",
    "echo '✅ Build verification completed'"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --timeout 30 --keep-alive 2 --log-level info --access-logfile - --error-logfile - app:app" 